### ISSUE TITLE
Creating a ARM64 image

### ISSUE THREAD

**Issue by SuicSoft** [pelya/debian-noroot#22]
I have a Nexus 9 which is a 64-bit Android tablet.I would like to compile for ARM64 to speed it up

**Comment by pelya** [comment]
You can replace armhf with arm64 in the debootstrap arguments in the
script. You will also need to replace proot binary in 'dist' with arm64
version before building an image:
https://github.com/proot-me/proot-static-build

**Comment by pelya** [comment]
Fixed in version 20.01.07
