### ISSUE TITLE
Is there a way to use openbox instead of xfce?

### ISSUE THREAD

**Issue by prahladyeri** [pelya/debian-noroot#33]
I know that xfce is very light, but I'd like something even lighter to conserve my tablet resources, is it possible to use openbox with debian-noroot? I'd also like to be able to hop into CLI mode and get rid of X entirely sometimes. On a usual machine, just killing xfce and X should drop you into the command line, but I'd like to know how does that work with debian-noroot?

This is a great software, by the way :+1: .

**Comment by pelya** [comment]
Try GNURoot Debian app, it's CLI-only version.

**Comment by prahladyeri** [comment]
I've already tried that but with GNURoot, installing X from scratch and using your xserver xsdl app is quite cumbersome. I need GUI too. I tried with lxde, but it failed to create a normal user session. The debian-noroot app is much better in comparison, getting to pure CLI isn't a big deal as my work is getting done, at least. Once again, quite a fantastic app.
