### ISSUE TITLE
No audio

### ISSUE THREAD

**Issue by ghost** [pelya/debian-noroot#35]
Well, there's actually more than this.
First, I tried gnuroot Debian with no luck connecting to xsdl.
Since x was working on Debian noroot, I thought to use it.
Lmms audio performance sucks, vlc won't either run and quod libet gives no sound.
Finally, Jack. I can't use it.
In my mind, I'd use blender and ardour with Jack, and nothing else. 
When starting jack I get a no such file or directory error. 
What can I do?
I have a Samsung Galaxy S5.

**Comment by user-e** [comment]
From the project README file:

> There are several limitations: [...]
> No audio support. Some time ago PulseAudio was somewhat supported, but now it's broken.

**Comment by pelya** [comment]
Fixed in version 20.01.07

**Comment by Pratham36** [comment]
> Fixed in version 20.01.07

No I facing this issue

**Comment by Pratham36** [comment]
Please tell how I fix

**Comment by Droidman007** [comment]
I got the solution you can use audio in debian noroot using termux
