### ISSUE TITLE
SD Card - permission denied

### ISSUE THREAD

**Issue by dothebart** [pelya/debian-noroot#41]
Hi, 
the desktop icon is there - however, clicking it gives a 'permission denied' 
is there a way to grant permission from the android UI?

**Comment by dothebart** [comment]
ok, got it. 
On the lock screen long press the 'Debian is running' tab, click the 'more settings' font. 
Now you're in the settings permisions of the app. 
Click on the headline, now you're in the main permissions tab. 
Click on `Permissions`
Check the only setting - 'storage'

**Comment by Safin252** [comment]
Bro still I'm getting permission denied issue... Sdcard, internal storage both aren't usable

**Comment by pelya** [comment]
I'm in the army right now so I can't help, sorry.

**Comment by Safin252** [comment]
Please help... Maybe just simple thing can fix this... 
![Screenshot_20231217-224547](https://github.com/pelya/debian-noroot/assets/152768049/93d5de6a-40c3-48ca-ad4c-c72cd87627f0)

**Comment by dothebart** [comment]
You should follow the path on the UI of the mobile that I put in above.

**Comment by Safin252** [comment]
You mean storage permission? It's always on allow button... 
![Screenshot_20231218-020802](https://github.com/pelya/debian-noroot/assets/152768049/a2ac222a-bc35-4de5-a3b5-08171a7782f8)
![Uploading Screenshot_20231218-020802.png…]()
