### ISSUE TITLE
playstore link is broken - apk alternative?

### ISSUE THREAD

**Issue by abubelinha** [pelya/debian-noroot#48]
The top of the main page links to Android Playstore, where it says:

> 
Debian running on Android, without rooting your phone https://play.google.com/store/apps/details?id=com.cuntubuntu

But the link is broken.  Can you provide the current working url?

If it is not in the playstore anymore, can you provide a link to a working .apk file?

Thanks

**Comment by pelya** [comment]
https://sourceforge.net/projects/libsdl-android/files/ubuntu/

It's removed from Play Store because it does not work on Android 6 and
above.

**Comment by abubelinha** [comment]
Thanks a lot for your prompt reply

What if I want to try it in an old version?
Can you provide an .apk file?

It would also be good a list of compatible Android versions 

Thanks in advance

**Comment by pelya** [comment]
Here: https://sourceforge.net/projects/libsdl-android/files/ubuntu/

Android 4-5: compatible
Android 6-10: incompatible
