### ISSUE TITLE
Rename this project

### ISSUE THREAD

**Issue by caspii** [pelya/debian-noroot#6]
Why on earth is it called **cuntubuntu**?

Either you're trying to be deliberately offensive or you have no idea you're being offensive.

In either case, you should consider renaming it

**Comment by pelya** [comment]
There are several reasons:

1. I was frustrated when my initial attempts to start Ubuntu UI using
fakechroot failed. Then I've modified fakechroot to actually launch
something, although poorly, and now I'm using proot, the best
virtualization solution for Android/Linux. I'm not as grumpy anymore as I
was back then, but the name remained.

2. Zero interest from Ubuntu community and management. My thread on Ubuntu
forums got a single reply that they can not help, Mark Shuttleworth did not
answer me on Reddit, all while pushing their failed attempt to make
dual-boot Ubuntu/Android devices, and releasing Ubuntu Touch for Nexus 7.
No one wants your Android-wannabe OS, Mark and Co, and you have missed that
smartphone money train, bitches.

3. Ubuntu requires newer kernel and works poorly with no graphical
acceleration. Newer versions of Ubuntu do not run on Android emulator
anymore, which I perceive as an arrogance. Debian keeps working everywhere,
even the unstable distribution, and it will not screw you up like Ubuntu
does every time when trying to update to the next major release. So now my
app is based on Debian, the best OS known to humankind.

4. Swearwords are fun! I was wondering if you could sneak in a curse into
Google Play package URL, and it turned up you totally can. And if someone
is getting offended by a mild usage of profanity, even not directed at them
personally, then <insert a photo of Linus flipping finger>.

Anyway, I'm okay with renaming the repository, even if for the sole reason
of removing Ubuntu references from it. But what should I call it?
Debian-noroot looks too obvious and boring. Maybe Huebian? But not everyone
will understand the reference, and it does not sound very good. I wonder if
Github accepts Unicode in repository names, maybe I'll be able to draw an
emoji penis.

**Comment by caspii** [comment]
Well, if I may offer you my advice, I'd say don't be bitter. About anything. It's not worth it. Also, in this case it comes across as a little unprofessional :wink:

But yeah, I'm sad about Ubuntu too. I'm the author of this blog article, by the way: http://old.kittysplit.com/blog/goodbye-ubuntu/

I'd don't get the Huebia reference either. My suggestions are 
* Andrebian
* Debdroid

Cool project, sadly I didn't have enough space on my phone for it to work

**Comment by pelya** [comment]
Github won't allow Unicode in repository name, it won't even allow = symbol to draw peins, so I've renamed it to boring debian-noroot, eh.
